### ISSUE TITLE
LVDS DIO rev2  Errata

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/DIO_RJ45#1]
_From @hartytp on [2017-07-24 17:20](https://github.com/sinara-hw/sinara/issues/242)_

- [x] Fix ordering of LEDs to match RJ45 connectors
- [x] Zero-index all channels
- [x] Invert/fix footprints of 0603 LEDs
- [x]  Please remove the annotation "This module connects to Kasli ..." and replace it with something like "EEM connector: IO are LVDS, I2C is 3V3 LVCMOS, P3V3_MP up to 20mA, P12V up to 1A."
- [x] Schematic needs a tidy up:
  - Remove annotations saying "ADD TVS!!!" (do we need to add TVS?)
  - First page should be title page, not LVDS buffer page
- [ ] Run off 2V5 to save power?
- [ ] Check output noise, do we need a bigger capacitor/LC filter?
- [x] Large clear note on the schematic + silk + docs that live switching of directions may result in damage.
- [x] Silk + schematic + panel should be "v1.x" not "rev1.x"
- [x] ground front panels

**Comment by marmeladapk** [comment]
_From @hartytp on [2017-07-24 17:21](https://github.com/sinara-hw/sinara/issues/242#issuecomment-317493121)_


@gkasprow Sorry for not picking up these issues in the previous design review!

**Comment by marmeladapk** [comment]
_From @gkasprow on [2017-07-24 18:51](https://github.com/sinara-hw/sinara/issues/242#issuecomment-317519353)_


I noticed them doing panel design. This should have been done in rev1 but there is so much work...

**Comment by marmeladapk** [comment]
_From @hartytp on [2017-07-24 20:37](https://github.com/sinara-hw/sinara/issues/242#issuecomment-317546883)_


No worries Greg -- you guys are tackling an intimidating number of hardware designs at the same time and making great progress, so a few minor things are bound to slip through!

These issues are only cosmetic and don't affect the boards' functionality. In any case, these boards are still prototypes, rather than production, so these kind of minor issues are expected :) 

At this point, I think the top priority is getting prototype hardware delivered to a few labs for thorough testing. We can always fix these small issues in rev2.

**Comment by marmeladapk** [comment]
_From @jordens on [2017-09-28 10:18](https://github.com/sinara-hw/sinara/issues/242#issuecomment-332793377)_


What does the QC sticker actually mean? On my 3U_DIO_RJ45 two pins of the RJ45 cage were not soldered.

**Comment by marmeladapk** [comment]
_From @gkasprow on [2017-09-28 12:58](https://github.com/sinara-hw/sinara/issues/242#issuecomment-332828285)_


@jordens could you take photo of this and send me? I'll ask Technosystem about it. QC means that it passed functional test.

**Comment by marmeladapk** [comment]
_From @jordens on [2017-09-28 13:31](https://github.com/sinara-hw/sinara/issues/242#issuecomment-332836912)_


Out of curiosity: what functional tests are being done?

I already soldered it myself. Photos of that probably won't help. Bottom corner of the cage.

![image](https://user-images.githubusercontent.com/1338946/30969197-f471d43a-a461-11e7-8b17-72adab5d85f7.png)

**Comment by marmeladapk** [comment]
_From @gkasprow on [2017-09-28 13:33](https://github.com/sinara-hw/sinara/issues/242#issuecomment-332837599)_


We tested propagation of signal through all ports in both directions and power consumption. Technosystem does AOI tests so we will investigate it.

**Comment by marmeladapk** [comment]
_From @jordens on [2017-09-28 14:29](https://github.com/sinara-hw/sinara/issues/242#issuecomment-332854395)_


Ok. Those tests sound good. Thanks!

**Comment by dtcallcock** [comment]
Both Technosystems and Creotech are out of stock and @akaminska is interested in fixing these issues before a new run.

**Comment by gkasprow** [comment]
@hartytp what do you meant by 

>Fix ordering of LEDs to match RJ45 connectors

**Comment by gkasprow** [comment]
2.5V is not enough for LEDs, we would need to add 3V3 rail anyway.

**Comment by gkasprow** [comment]
@hartytp OK, I found what you mean. row 1 and 2; 3 and 4 should be swapped.

**Comment by sbourdeauducq** [comment]
>     * Large clear note on the schematic + silk + docs that live switching of directions may result in damage.

Why? What is the damage mechanism?

**Comment by gkasprow** [comment]
It was an issue before I added 22R series resistors and stronger DC/DC converters. Before live switching caused momentary short circuit and overload of the converters. It caused some kind of latchup. I did not study the damage mechanism.
